module.exports = {
  apps: [
    {
      name: 'agenthunt-backend',
      cwd: './backend',
      script: 'dist/backend/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'production',
        UV_THREADPOOL_SIZE: 128,
        OTEL_ENABLED: 'true',
        PHOENIX_ENDPOINT: 'http://localhost:6006/v1/traces',
        OTEL_SERVICE_NAME: 'agenthunt',
      },
      error_file: '../logs/backend-error.log',
      out_file: '../logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'agenthunt-workers',
      cwd: './backend',
      script: 'dist/backend/src/workers.js',
      instances: 2, // Reduced instances for general workers
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '4G',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        UV_THREADPOOL_SIZE: 128,
        WORKER_QUEUES: 'discovery,subdomain,fingerprint,crawl,scanner,confirm,triage,interact,portscan,osint,xss,sqli,webvulns,jsanalysis,cloudmisconfig,three-agent', // General queues + three-agent
        OTEL_ENABLED: 'true',
        PHOENIX_ENDPOINT: 'http://localhost:6006/v1/traces',
        OTEL_SERVICE_NAME: 'agenthunt',
      },
      error_file: '../logs/workers-error.log',
      out_file: '../logs/workers-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'agenthunt-workers-high-cpu',
      cwd: './backend',
      script: 'dist/backend/src/workers.js',
      instances: 1, // Dedicated instance for high-CPU tasks
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '8G', // More memory for CPU-intensive tasks
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        UV_THREADPOOL_SIZE: 128,
        WORKER_QUEUES: 'bruteforce,high-cpu-queue', // High-CPU queues
        OTEL_ENABLED: 'true',
        PHOENIX_ENDPOINT: 'http://localhost:6006/v1/traces',
        OTEL_SERVICE_NAME: 'agenthunt',
      },
      error_file: '../logs/workers-high-cpu-error.log',
      out_file: '../logs/workers-high-cpu-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'agenthunt-workers-network-io',
      cwd: './backend',
      script: 'dist/backend/src/workers.js',
      instances: 1, // Dedicated instance for network I/O tasks
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '4G',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        UV_THREADPOOL_SIZE: 128,
        WORKER_QUEUES: 'network-io-queue', // Network I/O queues
        OTEL_ENABLED: 'true',
        PHOENIX_ENDPOINT: 'http://localhost:6006/v1/traces',
        OTEL_SERVICE_NAME: 'agenthunt',
      },
      error_file: '../logs/workers-network-io-error.log',
      out_file: '../logs/workers-network-io-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'agenthunt-frontend',
      cwd: './frontend',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
        NEXT_PUBLIC_API_URL: 'http://165.227.108.120:3000',
        NEXT_PUBLIC_WS_URL: 'ws://165.227.108.120:3000',
      },
      error_file: '../logs/frontend-error.log',
      out_file: '../logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
