/**
 * Manual Submission Templates
 * Provides templates for bug bounty platforms when user wants manual submission
 */
class SubmissionTemplateService {
  private static instance: SubmissionTemplateService;

  private constructor() {}

  public static getInstance(): SubmissionTemplateService {
    if (!SubmissionTemplateService.instance) {
      SubmissionTemplateService.instance = new SubmissionTemplateService();
    }
    return SubmissionTemplateService.instance;
  }

  /**
   * Generate HackerOne report template
   */
  public generateHackerOneTemplate(finding: any): string {
    return `## Summary
${finding.title}

## Description
${finding.description}

## Steps to Reproduce
${finding.poc.steps.map((step: string, i: number) => `${i + 1}. ${step}`).join('\n')}

## Supporting Material/References
${finding.poc.curl ? `### Request\n\`\`\`\n${finding.poc.curl}\n\`\`\`` : ''}

${finding.evidence && finding.evidence.length > 0 ? `### Evidence\n${finding.evidence.map((e: any, i: number) => `- Evidence ${i + 1}: ${e.type}`).join('\n')}` : ''}

## Impact
${finding.impact || 'See description for impact details'}

## Recommended Fix
${finding.remediation || 'Follow security best practices for this vulnerability type'}

## System Information
- **Finding ID**: ${finding.id}
- **Discovered**: ${new Date(finding.created_at).toLocaleString()}
- **Confidence**: ${Math.round(finding.confidence * 100)}%
- **CVSS Score**: ${finding.cvss || 'N/A'}
- **CWE**: ${finding.cwe?.join(', ') || 'N/A'}

---
*Report generated by AgentHunt Security Platform*
`;
  }

  /**
   * Generate Bugcrowd submission template
   */
  public generateBugcrowdTemplate(finding: any): string {
    return `**Title:** ${finding.title}

**Vulnerability Type:** ${finding.cwe?.[0] || 'Other'}

**Severity:** ${finding.severity}

**Description:**
${finding.description}

**Proof of Concept:**
${finding.poc.steps.map((step: string, i: number) => `${i + 1}. ${step}`).join('\n')}

${finding.poc.curl ? `\n**Request:**\n\`\`\`\n${finding.poc.curl}\n\`\`\`` : ''}

**Impact:**
${finding.impact || 'See description'}

**Remediation:**
${finding.remediation || 'Follow security best practices'}

**Additional Information:**
- Finding ID: ${finding.id}
- Confidence: ${Math.round(finding.confidence * 100)}%
- CVSS: ${finding.cvss || 'N/A'}
- Discovered: ${new Date(finding.created_at).toLocaleString()}

---
Generated by AgentHunt
`;
  }

  /**
   * Generate Intigriti report template
   */
  public generateIntigritiTemplate(finding: any): string {
    return `# ${finding.title}

## Vulnerability Details
- **Type**: ${finding.cwe?.[0] || 'N/A'}
- **Severity**: ${finding.severity}
- **CVSS**: ${finding.cvss || 'N/A'}

## Description
${finding.description}

## Reproduction Steps
${finding.poc.steps.map((step: string, i: number) => `${i + 1}. ${step}`).join('\n')}

## Proof of Concept
${finding.poc.curl || 'See steps above'}

## Impact
${finding.impact || 'Described in vulnerability description'}

## Mitigation
${finding.remediation || 'Apply security best practices'}

---
Report ID: ${finding.id}
Generated: ${new Date().toLocaleString()}
Platform: AgentHunt
`;
  }

  /**
   * Generate YesWeHack template
   */
  public generateYesWeHackTemplate(finding: any): string {
    return `## Title
${finding.title}

## Technical Environment
- Asset: ${finding.asset_value}
- Discovery Date: ${new Date(finding.created_at).toLocaleDateString()}

## Vulnerability Description
${finding.description}

## Steps to Reproduce
${finding.poc.steps.map((step: string, i: number) => `${i + 1}. ${step}`).join('\n')}

## Proof of Concept
\`\`\`
${finding.poc.curl || 'See reproduction steps'}
\`\`\`

## Business Impact
${finding.impact || 'See vulnerability description for impact'}

## Remediation Proposal
${finding.remediation || 'Apply appropriate security controls'}

## References
- CVSS: ${finding.cvss || 'N/A'}
- CWE: ${finding.cwe?.join(', ') || 'N/A'}
- Confidence: ${Math.round(finding.confidence * 100)}%

Finding Reference: ${finding.id}
`;
  }

  /**
   * Generate generic/custom template
   */
  public generateGenericTemplate(finding: any): string {
    return `VULNERABILITY REPORT

Title: ${finding.title}
Severity: ${finding.severity.toUpperCase()}
Asset: ${finding.asset_value}

DESCRIPTION
-----------
${finding.description}

REPRODUCTION STEPS
------------------
${finding.poc.steps.map((step: string, i: number) => `${i + 1}. ${step}`).join('\n')}

PROOF OF CONCEPT
----------------
${finding.poc.curl || 'See steps above'}

IMPACT
------
${finding.impact || 'See description'}

REMEDIATION
-----------
${finding.remediation || 'Apply security best practices'}

TECHNICAL DETAILS
-----------------
- Finding ID: ${finding.id}
- CVSS Score: ${finding.cvss || 'N/A'}
- CWE Classification: ${finding.cwe?.join(', ') || 'N/A'}
- Confidence Level: ${Math.round(finding.confidence * 100)}%
- Discovery Date: ${new Date(finding.created_at).toLocaleString()}
- Confirmation Status: ${finding.confirmations?.filter((c: any) => c.result === 'pass').length || 0} confirmations passed

Generated by AgentHunt Security Platform
${new Date().toLocaleString()}
`;
  }

  /**
   * Generate template based on platform
   */
  public generateTemplate(finding: any, platform: string): string {
    switch (platform.toLowerCase()) {
      case 'hackerone':
        return this.generateHackerOneTemplate(finding);
      case 'bugcrowd':
        return this.generateBugcrowdTemplate(finding);
      case 'intigriti':
        return this.generateIntigritiTemplate(finding);
      case 'yeswehack':
        return this.generateYesWeHackTemplate(finding);
      default:
        return this.generateGenericTemplate(finding);
    }
  }
}

export default SubmissionTemplateService.getInstance();
